model = "gpt-6-astra"
model_context_window = 400000
model_auto_compact_token_limit = 360000
model_reasoning_effort = "medium"
approval_policy = "on-request"
sandbox_mode = "workspace-write"
personality = "pragmatic"
approvals_reviewer = "guardian_subagent"
service_tier = "default"
model_verbosity = "medium"
model_reasoning_summary = "concise"

[features]
unified_exec = true
steer = true
multi_agent = true
apps = true
prevent_idle_sleep = true
terminal_resize_reflow = true
memories = true
goals = true
js_repl = false
chronicle = true

[features.context_management]
experimental_mode = true

[plugins."gmail@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."control-tower-dev@control-tower-plugins"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."computer-history@openai-bundled"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[marketplaces.openai-bundled]
last_updated = "2026-08-22T07:01:55Z"
source_type = "local"
source = "/Users/henrilemoine/dotfiles/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
source_type = "local"
source = "/Users/henrilemoine/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[marketplaces.control-tower-plugins]
source_type = "git"
source = "https://github.com/linuxarena/control-tower-plugins.git"

[desktop]
git-commit-instructions = "Follow codebase commit standard."
git-pr-instructions = "Be relatively concise / conscious of people's time to read. Be detailed when there's relevant details, less so when there's less."
followUpQueueMode = "steer"
dock-icon-preference = "app-default"
keepRemoteControlAwakeWhilePluggedIn = true
conversationDetailMode = "STEPS_COMMANDS"
defaultTerminalLocation = "right"
preventSleepWhileRunning = true
show-context-window-usage = true
notifications-turn-mode = "unfocused"
enabled-reasoning-efforts = ["low", "medium", "high", "xhigh", "max"]
selected-avatar-id = "custom:black-sphere"
avatar-overlay-mascot-width-px = 80
open-link-in-target-preference = "external-browser"
git-pull-request-merge-method = "squash"
reviewDelivery = "detached"
worktree-keep-count = 1500
"browser-family-enabled:chrome" = false
browser-show-full-url = true

[desktop.open-in-target-preferences]
global = "terminal"
